base_url = "/"
compile_sass = true
build_search_index = true

taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "dracula"
smart_punctuation = true
render_shortcodes = true
generate_toc = true
extra_syntaxes_and_themes = ["syntaxes/lean.sublime-syntax"]


[extra]
image = "og_image.png"
favicon = "favicon.ico"
twitter_card = true
twitter_title = "/autoparallel/"
twitter_url = "https://autoparallel.xyz/"
twitter_description = ">>> going with the flow >>>"
twitter_image = "og_image.png"
header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/braindump", name_en = "/braindump/" },
    { url = "/longform", name_en = "/longform/" },
]
